### ISSUE TITLE
Request integration training

### ISSUE THREAD

**Issue by mohammad-y** [kleeja-official/vbulletin-integration#1]
In earlier versions of Kleeja it was easy to integrate with Vibuletin.
There are some issues with the new version at this time

1- There is no olang language file. Screen shot:

![Sc](https://user-images.githubusercontent.com/30681568/77533565-bcdd2680-6eb4-11ea-8b3b-b49c79da1732.png)

2- {olang.VBULLETIN_INTR_ENABLE} is disabled in settings and there is no way to change it.

3- There are no guidelines for the integration process

**Comment by abdumu** [comment]
delete the plugin and install it again.
